jobs:
  RunOnLinux:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Grant Permission
      run: sudo chmod +x ./mvnw
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: '11'
    - continue-on-error: true
      name: Run Tests
      run: ./mvnw -B -ntp clean test
  RunOnMacOs:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Grant Permission
      run: sudo chmod +x ./mvnw
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: '11'
    - continue-on-error: true
      name: Run Tests
      run: ./mvnw -B -ntp clean test
  RunOnWindows:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: '11'
    - continue-on-error: true
      name: Run Tests
      run: ./mvnw.cmd -B -ntp clean test
name: Build PR
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
