jobs:
  Publish:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Grant Permission
      run: sudo chmod +x ./mvnw
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: '11'
    - continue-on-error: true
      name: Remove old Maven Settings
      run: rm -f /home/runner/.m2/settings.xml
    - continue-on-error: true
      name: Maven Settings
      uses: s4u/maven-settings-action@v2.2.0
      with:
        servers: "[{\n  \"id\": \"ossrh\",\n  \"username\": \"${{ secrets.OSSRH_USERNAME\
          \ }}\",\n  \"password\": \"${{ secrets.OSSRH_PASSWORD }}\"\n}]\n"
    - continue-on-error: true
      name: Import GPG
      uses: crazy-max/ghaction-import-gpg@v5.2.0
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
    - continue-on-error: true
      name: Build
      run: mvn -ntp -B clean verify install -DskipTests
    - continue-on-error: true
      env:
        GPG_KEY_NAME: ${{ secrets.GPG_KEY_NAME }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      name: Publish to Maven Central
      run: mvn -ntp -B deploy -DskipTests -Dgpg.keyname=${GPG_KEY_NAME} -Dgpg.passphrase=${GPG_PASSPHRASE}
name: Release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
